[project]
name = "the-hitchhikers-guide-to-asyncio"
version = "0.1.0"
description = "Code for the talk 'The Hitchhiker's Guide to Asyncio'"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.27.2",
]
